# Delay between shots in milliseconds
quake-gun-delay: 5000
quake-gun-damage: 20
quake-gun-distance: 60

throwing-knives-damage: 5
throwing-knives-distance: 10

bridge-block-expiry-ms: 5000

rebound-bow-bounces: 2
rebound-bow-spread: 0
rebound-bow-damage-amplifier: 1.2

kunai-damage: 20